Repository trinodb/trino-gateway, pull requests merged in 2024-02, with the labels that each got.

#228 Replace deprecated Request.header method
  gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java
Labels: cla-signed

#145 Replace ActiveJDBC with JDBI for QueryHistory
  gateway-ha/pom.xml
  gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/JdbcConnectionManager.java
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/RecordAndAnnotatedConstructorMapper.java
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistory.java
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistoryDao.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/HaQueryHistoryManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/HaGatewayTestUtils.java
  gateway-ha/src/test/java/io/trino/gateway/ha/TestTrinoResource.java
  gateway-ha/src/test/java/io/trino/gateway/ha/TestingJdbcConnectionManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaRoutingManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryHistoryManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestSpecificDbResourceGroupsManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueueLengthRoutingTable.java
  pom.xml
Labels: cla-signed

#236 Remove unused code
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ExactMatchSourceSelectors.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueueLengthRoutingTable.java
  gateway-ha/src/main/java/io/trino/gateway/ha/security/AuthorizationManager.java
  gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyHandler.java
  gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyServer.java
  gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbFilter.java
Labels: cla-signed

#234 Refactor rewriteTarget
  gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java
Labels: cla-signed

#237 Avoid using TestMethodOrder in TestHaGatewayManager
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java
Labels: cla-signed

#235 Inline dependency version
  gateway-ha/pom.xml
  pom.xml
Labels: cla-signed

#232 Use builder for ClusterStats
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStats.java
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsJdbcMonitor.java
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsObserver.java
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/HealthCheckObserver.java
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/HealthChecker.java
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/NoopClusterStatsMonitor.java
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/TrinoQueueLengthChecker.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/BackendStateManager.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java
Labels: cla-signed

#240 Remove unused code
  gateway-ha/gateway-ha-config-docker.yml
  gateway-ha/gateway-ha-config.yml
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ActiveClusterMonitor.java
  gateway-ha/src/main/java/io/trino/gateway/ha/config/MonitorConfiguration.java
Labels: cla-signed

#243 Remove unused field
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStats.java
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
Labels: cla-signed

#252 Remove redundant try-catch from PublicResource
  gateway-ha/src/main/java/io/trino/gateway/ha/resource/PublicResource.java
Labels: cla-signed

#250 Remove restart policy from docker compose file
  docker/gateway-compose.yml
  docker/postgres-backend-compose.yml
Labels: cla-signed

#231 Use JDBI for gateway_backend
  gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/GatewayBackend.java
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/GatewayBackendDao.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaRoutingManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueueLengthRoutingTable.java
Labels: cla-signed

#230 Use JDBI for resource_groups_global_properties
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/JdbcConnectionManager.java
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ResourceGroupsGlobalProperties.java
  gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ResourceGroupsGlobalPropertiesDao.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/HaResourceGroupsManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestSpecificDbResourceGroupsManager.java
Labels: cla-signed

#209 Improve docker setup and docs
  docker/README.md
  docker/build.sh
  docker/container-test.sh
  docker/docker-compose.yml
  docker/postgres-backend-compose.yml
  docker/trino-gateway-compose.yml
  docs/development.md
Labels: cla-signed

#196 Add release notes for Trino Gateway 6
  docs/release-notes.md
Labels: cla-signed

#257 Avoid test run in release build
  pom.xml
Labels: cla-signed

#262 Remove unused variable
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueueLengthRoutingTable.java
Labels: cla-signed

#258 Import String.format method statically
  gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/HealthChecker.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/ConnectionChecker.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/HaResourceGroupsManager.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/RuleReloadingRoutingGroupSelector.java
  gateway-ha/src/main/java/io/trino/gateway/ha/security/LbOAuthManager.java
  gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestQueryIdCachingProxyHandler.java
  gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbFilter.java
Labels: cla-signed, maintenance, no-release-notes

#261 Remove unused mock
  gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthenticator.java
Labels: cla-signed

#246 Remove unused classes and file
  gateway-ha/src/main/java/io/trino/gateway/ha/router/ConnectionCheck.java
  gateway-ha/src/main/java/io/trino/gateway/ha/router/ConnectionChecker.java
  gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTcpChecks.java
  gateway-ha/src/test/resources/rules/routing_rules_tcp_connection.yml
Labels: cla-signed

#266 allow customization of test containers image name
  gateway-ha/src/test/java/io/trino/gateway/CustomTrinoImageNameSubstitutor.java
  gateway-ha/src/test/resources/testcontainers.properties
Labels: cla-signed, no-release-notes

#267 Disallow JUnit assertions
  pom.xml
Labels: cla-signed, no-release-notes
